Updated to fix deployments - auth
error: unable to recognize "deployments/hello.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"