Removed field 'track' to fix error
The field 'track' is not recognized and gives error so it is removed.

$ kubectl create -f deployments/hello.yaml
error: error validating "deployments/hello.yaml": error validating data: [ValidationError(Deployment.spec.selector): unknown field "app" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector, ValidationError(Deployment.spec.selector): unknown field "track" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector]; if you choose to ignore these errors, turn validation off with --validate=false